name: scan
on:
  push: 
    branches:
      - "dev"
  # pull_request:
  #   branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build an image from Dockerfile
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ls